[immich] fix conflicting custom ports #66

diff --git a/immich/rootfs/etc/s6-overlay/s6-rc.d/init-nginx/run b/immich/rootfs/etc/s6-overlay/s6-rc.d/init-nginx/run
--- a/immich/rootfs/etc/s6-overlay/s6-rc.d/init-nginx/run
+++ b/immich/rootfs/etc/s6-overlay/s6-rc.d/init-nginx/run
@@ -15,39 +15,33 @@ bashio::var.json \
         -template /etc/nginx/templates/upstream.gtpl \
         -out /etc/nginx/includes/upstream.conf
 
-# Generate direct access configuration, if enabled.
-if bashio::var.has_value "$(bashio::addon.port 8080)"; then
-    # Require certfile and keyfile if ssl is true
-    #bashio::config.require.ssl
+if bashio::config.true 'ssl'; then
+    # Require certfile and keyfile
+    #bashio::config.require 'certfile'
+    #bashio::config.require 'keyfile'
 
-    if bashio::config.true 'ssl'; then
-        # Require certfile and keyfile
-        #bashio::config.require 'certfile'
-        #bashio::config.require 'keyfile'
+    # If certfile or keyfile does not exist, generate self-signed cert
+    if ! bashio::fs.file_exists "$certfile" || ! bashio::fs.file_exists "$keyfile"; then
+        bashio::log.warning "SSL is enabled, but certfile or keyfile is missing. Using self-signed certificate..."
 
-        # If certfile or keyfile does not exist, generate self-signed cert
-        if ! bashio::fs.file_exists "$certfile" || ! bashio::fs.file_exists "$keyfile"; then
-            bashio::log.warning "SSL is enabled, but certfile or keyfile is missing. Using self-signed certificate..."
+        certfile="/data/ssl/fullchain.pem"
+        keyfile="/data/ssl/privkey.pem"
 
-            certfile="/data/ssl/fullchain.pem"
-            keyfile="/data/ssl/privkey.pem"
-
-            /usr/local/bin/selfsigned-ssl-gen.sh "$certfile" "$keyfile"
-        fi
-
-        echo "$certfile" > /var/run/s6/container_environment/SSL_CERTFILE
-        echo "$keyfile" > /var/run/s6/container_environment/SSL_KEYFILE
+        /usr/local/bin/selfsigned-ssl-gen.sh "$certfile" "$keyfile"
     fi
 
-    bashio::var.json \
-        certfile "$certfile" \
-        keyfile "$keyfile" \
-        port "^$(bashio::addon.port 8080)" \
-        protocol "${immich_protocol}" \
-        ssl "^$(bashio::config 'ssl')" \
-        | tempio \
-            -template /etc/nginx/templates/direct.gtpl \
-            -out /etc/nginx/servers/direct.conf
+    echo "$certfile" > /var/run/s6/container_environment/SSL_CERTFILE
+    echo "$keyfile" > /var/run/s6/container_environment/SSL_KEYFILE
 fi
+
+bashio::var.json \
+    certfile "$certfile" \
+    keyfile "$keyfile" \
+    port "8080" \
+    protocol "${immich_protocol}" \
+    ssl "^$(bashio::config 'ssl')" \
+    | tempio \
+        -template /etc/nginx/templates/direct.gtpl \
+        -out /etc/nginx/servers/direct.conf
 
 exec cron &
