[nextcloud] mariadb auto upgrade

diff --git a/nextcloud/rootfs/etc/s6-overlay/s6-rc.d/init-mariadb-upgrade/run b/nextcloud/rootfs/etc/s6-overlay/s6-rc.d/init-mariadb-upgrade/run
--- a/nextcloud/rootfs/etc/s6-overlay/s6-rc.d/init-mariadb-upgrade/run
+++ b/nextcloud/rootfs/etc/s6-overlay/s6-rc.d/init-mariadb-upgrade/run
@@ -4,24 +4,11 @@
 if [[ "${#MYSQL_ROOT_PASSWORD}" -gt "3" ]]; then
     # display a message about upgrading database if needed
     if mariadb-upgrade -u root -p"${MYSQL_ROOT_PASSWORD}" --check-if-upgrade-is-needed >/dev/null 2>&1; then
-        cat <<-EOF
-
-
-
-#################################################################
-#                                                               #
-#           An upgrade is required on your databases.           #
-#                                                               #
-#         Stop any services that are accessing databases        #
-#          in this container, and then run the command          #
-#                                                               #
-#             mariadb-upgrade -u root -p<PASSWORD>              #
-#                                                               #
-#################################################################
-
-
-
-EOF
-        sleep 5s
+        echo "Upgrading MariaDB, this could take some time!"
+        echo "Don't stop the add-on!"
+        if ! mariadb-upgrade -u root -p"${MYSQL_ROOT_PASSWORD}"; then
+            echo "Error: MariaDB upgrade failed!" >&2
+            exit 1
+        fi
     fi
 fi
